# -*- coding: utf-8 -*-
"""ARIMA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sVmJNSjYUIGltx2G4BvvjmsuaMhXE4i8
"""

import numpy 
from statsmodels.tsa.statespace.sarimax import SARIMAX

class method():
  
  def __init__(self, method_parameters):
    self.ar_terms = method_parameters.get('ar_terms')
    self.seasonal_ar_terms = method_parameters.get('seasonal_ar_terms')
    self.differencing_terms = method_parameters.get('differencing_terms')
    self.seasonal_differencing_terms = method_parameters.get('seasonal_differencing_terms')
    self.ma_terms = method_parameters.get('ma_terms')
    self.seasonal_ma_terms = method_parameters.get('seasonal_ma_terms')
    self.seasonal_period = method_parameters.get('seasonal_period')
    self.trend = method_parameters.get('trend')

    self.order = (self.ar_terms, self.differencing_terms, self.ma_terms)
    self.seasonal_order = (self.seasonal_ar_terms, self.seasonal_differencing_terms, self.seasonal_ma_terms, self.seasonal_period)

  #main method
  def reshape_data_to_predict(self, data_to_reshape, outcome_variable, time_variable):
    data = numpy.array([value for value in data_to_reshape[outcome_variable].values])
    return data

  def predict(self, values):
    values = self.impute_non_positive_values(values)
    prediction = self.get_prediction(values)
    return prediction
  
  def update_reshaped_data(self, reshaped_data, new_observation):
    return numpy.append(reshaped_data, new_observation)
  
  #subsidiary methods
  def impute_non_positive_values(self, values):
    values[values == 0] = 0.0001
    return values

  def get_prediction(self, values):
    try:
      model = SARIMAX(values, order=self.order,\
                      seasonal_order=self.seasonal_order, trend=self.trend,\
                      enforce_stationarity=False, enforce_invertibility=False)
      model_fit = model.fit(disp=False)
      prediction = model_fit.predict(len(values), len(values))[0]
    except:
      prediction = None
    return prediction