# -*- coding: utf-8 -*-
"""CNN

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EtdZRJJwW5wXYevUIsQNudM21qWY7uqY
"""

class cnn_method():
  pass