# -*- coding: utf-8 -*-
"""CNN_LSTM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z-bjJ5E-I7L1lOMOYLo9UfNJ1S8xW66P
"""

class cnn_lstm_method():
  pass