# -*- coding: utf-8 -*-
"""ConvLSTM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bu22EkwZxMLtmXLIrB3gXmNc1EjqvXGI
"""

class convlstm_method():
  pass