# -*- coding: utf-8 -*-
"""LSTM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZtNKy_moEdGnIIy_olOPX7lYq4fpBrGa
"""

class lstm_method():
  pass