# -*- coding: utf-8 -*-
"""MLP

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V3XYVJDAIRPPgL_ekkt1HlwGmCpst9s6
"""

class mlp_method():
  pass