# -*- coding: utf-8 -*-
"""RF

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ligX_X6gYf6EbhmRm7PWBiRQcWYQa8PJ
"""
import numpy
import pandas 
from sklearn.ensemble import RandomForestRegressor

class method():
  
  def __init__(self, method_parameters):
    self.number_input_lags = method_parameters.get('number_input_lags')
    self.number_output_leads = method_parameters.get('number_output_leads')
    self.minimum_samples_leaf = method_parameters.get('minimum_samples_leaf')
    self.maximum_number_features = method_parameters.get('maximum_number_features')
    self.number_trees = method_parameters.get('number_trees')

  #main
  def reshape_data_to_predict(self, data_to_reshape, outcome_variable, time_variable):
    data_to_reshape = pandas.DataFrame(data_to_reshape)
    columns = list()
    #input sequence (t-n, ....,t-1)
    for i in range(self.number_input_lags, 0, -1):
      lags = data_to_reshape.groupby(time_variable)[outcome_variable].shift(i)
      lags.name = outcome_variable + '_lag_' + str(i)
      columns.append(lags)
    #forecast sequence (t, t+1, ...., t+n)
    for i in range(0, self.number_output_leads):
      leads = data_to_reshape.groupby(time_variable)[outcome_variable].shift(-i)
      columns.append(leads)
    #put it all together
    data = pandas.concat(columns, axis=1)
    #drop rows with NAs 
    data.dropna(inplace=True)
    return data

  def predict(self, values):
    prediction = self.get_prediction(values)
    return prediction

  def update_reshaped_data(self, reshaped_data, new_observation):
    new_observation = numpy.append(reshaped_data.iloc[-1,:].values[1:], [new_observation]).reshape(1, self.number_input_lags + 1)
    reshaped_data.loc[reshaped_data.index[-1]+1,:] = new_observation
    return reshaped_data
  
  #subsidiary
  def get_prediction(self, values):
    #try:
    model = RandomForestRegressor(n_estimators = self.number_trees,\
                                  min_samples_leaf = self.minimum_samples_leaf,\
                                  max_features = self.maximum_number_features)
    X, y = values.iloc[:, :-1].values, values.iloc[:,-1].values
    model_fit = model.fit(X, y)
    X_input =  values.iloc[-1][1:].values.reshape(1, self.number_input_lags)
    prediction = model_fit.predict(X_input)[0]
    #except:
      #prediction = None
    return prediction