# -*- coding: utf-8 -*-
"""2DLSTM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iSAs47wM3hCmosuFcy9CriRtxO4daOee
"""

class twoDlstm_method():
  pass